-- =========================================================================
-- SQL INSERT KHUSUS ISIAN SASARAN PRIORITAS NASIONAL (RKP)
-- Tabel: rkp_ps_pn_sasaran & rkp_ps_pn_indikator
-- =========================================================================

-- 1. INSERT DATA SASARAN PRIORITAS NASIONAL (rkp_ps_pn_sasaran)
INSERT INTO `rkp_ps_pn_sasaran` (`Id`, `_IdPN`, `Sasaran`, `created_at`, `updated_at`, `deleted_at`) VALUES
('1', '1', 'Terwujudnya kehidupan bermasyarakat, berbangsa, dan bernegara yang berlandaskan Pancasila, demokrasi, dan hak asasi manusia', NOW(), NOW(), NULL),
('2', '2', 'Terjaganya kedaulatan negara dan penguatan stabilitas keamanan nasional sebagai fondasi pelaksanaan pembangunan', NOW(), NOW(), NULL),
('3', '2', 'Meningkatkan kemandirian bangsa dalam memenuhi kebutuhan pangan yang berkualitas secara berkelanjutan dengan pendekatan nexus pangan, energi. dan air (FEW Nexus)', NOW(), NOW(), NULL),
('4', '2', 'Meningkatkan kemandirian bangsa dalam memenuhi kebutuhan energi secara berkelanjutan. dengan pendekatan nexus pangan, energi, dan air (FEW Nexus', NOW(), NOW(), NULL),
('5', '2', 'Meningkatkan kemandirian bangsa dalam memenuhi kebutuhan air secara berkelanjutan dengan pendekatan nexus pangan, energi, dan air (FEW Nexus)', NOW(), NOW(), NULL),
('6', '2', 'Terwujudnya perekonomian nasional yang inklusif dan berkelanjutan', NOW(), NOW(), NULL),
('7', '2', 'Terwujudnya transformasi ekonomi hijau', NOW(), NOW(), NULL),
('8', '3', 'Terwujudnya pengembangan infrastruktur yang berkelanjutan', NOW(), NOW(), NULL),
('9', '3', 'Meningkatnya total aset sektor keuangan terhadap PDB', NOW(), NOW(), NULL),
('10', '3', 'Meningkatnya lapangan kerja yang berkualitas', NOW(), NOW(), NULL),
('11', '3', 'Meningkatnya nilai tambah pariwisata', NOW(), NOW(), NULL),
('12', '3', 'Meningkatnya proporsi PDB ekonomi kreatif', NOW(), NOW(), NULL),
('13', '4', 'Terwujudnya pendidikan berkualitas yang merata', NOW(), NOW(), NULL),
('14', '4', 'Terwujudnya kesehatan untuk semua', NOW(), NOW(), NULL),
('15', '4', 'Terwujudnya keluarga berkualitas, kesetaraan gender, dan masyarakat inklusif', NOW(), NOW(), NULL),
('16', '4', 'Menguatnya iptek, inovasi, dan produktivitas tenaga kerja', NOW(), NOW(), NULL),
('17', '4', 'Meningkatnya prestasi olahraga Indonesia di tingkat dunia dan budaya berolahraga di masyarakat', NOW(), NOW(), NULL),
('18', '5', 'Terwujudnya peningkatan nilai tambah, produktivitas dan daya saing industri pengolahan', NOW(), NOW(), NULL),
('19', '5', 'Terwujudnya peningkatan integrasi ekonomi domestik dan global', NOW(), NOW(), NULL),
('20', '6', 'Mempercepat pengurangan kemiskinan dan peningkatan pemerataan', NOW(), NOW(), NULL),
('21', '6', 'Meningkatnya akses hunian layak, terjangkau, dan berkelanjutan', NOW(), NOW(), NULL),
('22', '6', 'Mewujudkan pembangunan kemandirian perdesaan dari bawah sebagai sumber pertumbuhan ekonomi yang berkelanjutan', NOW(), NOW(), NULL),
('23', '6', 'Perkotaan sebagai pusat pertumbuhan ekonomi', NOW(), NOW(), NULL),
('24', '7', 'Terwujudnya supremasi hukum yang transparan, adil, dan tidak memihak serta sistem politik yang fungsional', NOW(), NOW(), NULL),
('25', '7', 'Terwujudnya birokrasi pemerintahan yang adaptif dan melayani', NOW(), NOW(), NULL),
('26', '7', 'Terwujudnya masyarakat yang bebas dari penyalahgunaan narkoba', NOW(), NOW(), NULL),
('27', '7', 'Terwujudnya tata kelola BUMN yang baik untuk meningkatkan kontribusi BUMN sebagai agen pembangunan', NOW(), NOW(), NULL),
('28', '7', 'Tercapainya peningkatan pendapatan negara yang optimal dengan tetap menjaga iklim investasi, didukung upaya mewujudkan reformasi fiskal secara komprehensif melalui optimalisasi belanja negara serta perluasan sumber dan pengembangan inovasi pembiayaan', NOW(), NOW(), NULL),
('29', '7', 'Tercapainya tingkat inflasi yang rendah dan stabil untuk mendukung stabilitas serta pertumbuhan ekonomi yang inklusif dan berkelanjutan', NOW(), NOW(), NULL),
('30', '8', 'Terwujudnya kehidupan beragama yang maslahat dan berkebudayaan maju', NOW(), NOW(), NULL),
('31', '8', 'Terwujudnya resiliensi terhadap bencana dan perubahan iklim', NOW(), NOW(), NULL);

-- 2. INSERT DATA INDIKATOR SASARAN PRIORITAS NASIONAL (rkp_ps_pn_indikator)
INSERT INTO `rkp_ps_pn_indikator` (`Id`, `_IdSasaranPN`, `Indikator`, `Satuan`, `Baseline`, `TargetAwal`, `TargetAkhir`, `Pengampu`, `created_at`, `updated_at`, `deleted_at`) VALUES
('1', '1', 'Indeks Demokrasi Indonesia', NULL, NULL, '81,69-85,23', '83,42-86,96', 'Kementerian Koordinator Bidang Politik dan Keamanan', NOW(), NOW(), NULL),
('2', '1', 'Indeks Hak Asasi Manusia', NULL, '2,70 (2023)', '2,75', '2,85', 'Kementerian Hak Asasi Manusia', NOW(), NOW(), NULL),
('3', '2', 'Asia Power Index (Diplomatic Influence)', NULL, '65.6', '65.7', '66.1', 'Kementerian Luar Negeri', NOW(), NOW(), NULL),
('4', '2', 'Asia Power Index (Military Capability)', NULL, '15.7', '16', '20', 'Kementerian Koordinator Bidang Politik dan Keamanan', NOW(), NOW(), NULL),
('5', '2', 'Proporsi penduduk yang merasa aman berjalan sendirian di area tempat tinggalnya', 'persen', '62,8 (2020)', '67.5', '68.5', 'Kementerian Koordinator Bidang Politik dan Keamanan', NOW(), NOW(), NULL),
('6', '2', 'Global Cybersecurity Index', NULL, '100', '100', '98', 'Kementerian Koordinator Bidang Politik dan Keamanan', NOW(), NOW(), NULL),
('7', '2', 'Indeks Keamanan Laut Nasional', NULL, '59', '60', '64', 'Kementerian Koordinator Bidang Politik dan Keamanan', NOW(), NOW(), NULL),
('8', '3', 'Indeks Ketahanan Pangan (IKP)', NULL, '71.2', '73.2', '82', 'Kementerian Koordinator Bidang Pangan', NOW(), NOW(), NULL),
('9', '3', 'Pertumbuhan PDB pertanian, kehutanan, dan perikanan', 'persen', '1,30 (2023)', '2.20', '3.46', 'Kementerian Koordinator Bidang Pangan', NOW(), NOW(), NULL),
('10', '4', 'Indeks Ketahanan Energi', NULL, '6.64', '6.77', '6.95', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('11', '5', 'Indeks Ketahanan. Air Nasional', NULL, '3,48 (2022)', '3.5', '3.75', 'Kementerian Koordinator Bidang Infrastruktur dan Pembangunan Kewilayahan', NOW(), NOW(), NULL),
('12', '6', 'Posisi ekonomi syariah Indonesia di tingkat global (Peringkat GIEI)', 'Peringkat', '3', '3', '1', 'Komite Nasional Ekonomi dan Keuangan Syariah (KNEKS)', NOW(), NOW(), NULL),
('13', '6', 'Indonesia Blue Economy Index (IBEI)', NULL, '34,25 (2023)', '38.76', '50.73', 'Kementerian PPN/BAPPENAS', NOW(), NOW(), NULL),
('14', '6', 'Indeks Daya Saing Digital di Tingkat Global', 'Peringkat', '45 (2023)', '43', '40', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('15', '7', 'Indeks Ekonomi Hijau', NULL, '60,08 (2023)', '68.34', '77.2', 'Kementerian PPN/BAPPENAS', NOW(), NOW(), NULL),
('16', '7', '-Indeks Kualitas Lingkungan Hidup', NULL, '72,54 (2023)', '76.49', '77.2', 'Kementerian Lingkungan Hidup/Badan Pengendalian Lingkungan Hidup', NOW(), NOW(), NULL),
('17', '7', 'Indeks Pengelolaan Keanekaragaman Hayati', NULL, '0,35 (2020)', '0.44', '0.55', 'Kementerian Lingkungan Hidup/Badan Pengendalian Lingkungan Hidup', NOW(), NOW(), NULL),
('18', '8', 'Stok infrastruktur terhadap PDB', 'persen', '43,00 (2019)', '46.5', '48.5', 'Kementerian Koordinator Bidang Infrastruktur dan Pembangunan Kewilayahan', NOW(), NOW(), NULL),
('19', '9', 'Total aset sektor keuangan/PDB', 'persen', '170,5 (2023)', '188.5', '213.6', 'Otoritas Jasa Keuangan', NOW(), NOW(), NULL),
('20', '10', 'Proporsi penciptaan lapangan kerja formal', 'persen', '23.96', '35', '46', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('21', '11', 'Rasio PDB pariwisata', 'persen', '3,60 (2022)', '4,50-4,60', '4,90-5,00', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('22', '11', 'Devisa pariwisata', 'miliar USD', '14,00 (2023)', '19,00-22,10', '32,00-39,40', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('23', '12', 'Proporsi PDB ekonomi kreatif', 'persen', '6,77 (2023)', '7,3-7,9', '8,0-8,4', 'Kementerian Koordinator Bidang Pemberdayaan Masyarakat', NOW(), NOW(), NULL),
('24', '13', 'Rata-rata nilai PISA: (a) membaca; (b) matematika; (c) sains', NULL, '(a) 359; (a) 396; (a) 409; (2022)', '(b) 366; (b) 404; (b) 416;', '(c) 383 (c) 416 (c) 426', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('25', '13', 'Rata-rata lama sekolah penduduk usia di atas 15 tahun', 'tahun', '9.22', '9.22', '9.33', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL);
INSERT INTO `rkp_ps_pn_indikator` (`Id`, `_IdSasaranPN`, `Indikator`, `Satuan`, `Baseline`, `TargetAwal`, `TargetAkhir`, `Pengampu`, `created_at`, `updated_at`, `deleted_at`) VALUES
('26', '13', 'Harapan lama sekolah', 'tahun', '13.21', '13.32', '13.58', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('27', '13', 'Persentase pekerja lulusan pendidikan menengah dan tinggi yang bekerja di bidang keahlian menengah dan tinggi', 'persen', '66,30 (2023)', '66.78', '67.66', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('28', '13', 'Proporsi penduduk berusia 15 tahun ke atas yang berkualifikasi pendidikan tinggi', 'persen', '10,15 (2023)', '2026-11-11 00:00:00', '12.68', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('29', '13', '06 Rata-rata nilai asesmen tingkat nasional: (a) literasi membaca; (b) numerasi', NULL, '(a) 60,89; (b) 51,36 (2023)', '(a) 62,89; (b) 54,36', '(a) 66,89; (b) 59,86', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('30', '14', 'Usia harapan hidup (UHH)', 'tahun', '72,13 (2023)', '74.43', '75.4', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('31', '14', 'Angka kelahiran total (Total fertility rate)', 'rata-rata kelahiran per wanita usia subur (WUS) 15-49 Tahun', '2,14 (2023)', '2.12', '2.1', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('32', '15', 'ndeks Ketimpangan Gender (IKG)', NULL, '0,447 (2023)', '0.43', '0.394', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('33', '15', 'Indeks Pembangunan Kualitas Keluarga', NULL, '69,51 (2023)', '72.89', '75.55', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('34', '15', 'Indeks Pembangunan Pemuda', NULL, '60,59 (2023)', '65.16', '73.27', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('35', '15', '- Indeks Pembangunan Gender', NULL, '91,85 (2023)', '92,02-92,11', '92,34-92,54', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('36', '15', '- Indeks Perlindungan Anak', NULL, '68,29 (2023)', '70.19', '75.29', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('37', '15', 'Mobilitas penduduk lanjut usia', 'persen', '92,94 (2023)', '94', '96', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('38', '15', 'Mobilitas penduduk penyandang disabilitas', 'persen', '68,42 (2023)', '69', '71', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('39', '16', 'Tingkat pengangguran terbuka', 'persen', '4.91', '4,50-5,00', '4,00-4,71', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('40', '16', 'Peringkat indeks. inovasi global', 'peringkat', '54', '53', '49', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('41', '17', 'Jumlah perolehan medali emas pada olympic games', 'medali', '2', '4-6 (2028)', NULL, 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('42', '17', 'Jumlah perolehan medali emas pada paralympic games', 'medali', '1', '4-6 (2028)', NULL, 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('43', '17', 'Peringkat pada Asian Games', 'peringkat', '13 (2023)', '9-11 (2026)', NULL, 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('44', '17', 'Peringkat pada Asian Para Games', 'peringkat', '6 (2023)', '5-7 (2026)', NULL, 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('45', '17', 'Peringkat pada SEA Games peringkat', NULL, '3 (2023)', '3', '2026-04-02 00:00:00', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('46', '17', 'Peringkat pada ASEAN Para Games', 'peringkat', '1 (2023)', '1-2 (2029', NULL, 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('47', '17', 'Persentase penduduk berumur 10 tahun ke atas yang aktif berolahraga', 'persen', '9.04', '10,36-11-45', '12,13-13,40', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('48', '18', 'Rasio PDB Industri Pengolahan', 'persen', '18,67 (2023)', '20.8', '21.9', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('49', '19', 'Biaya logistik', 'persen PDB', '18,67 (2023)', '13.52', '12.5', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('50', '19', 'Pembentukan modal tetap bruto', 'persen PDB', '29,3 (2023)', '29.4', '29.9', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL);
INSERT INTO `rkp_ps_pn_indikator` (`Id`, `_IdSasaranPN`, `Indikator`, `Satuan`, `Baseline`, `TargetAwal`, `TargetAkhir`, `Pengampu`, `created_at`, `updated_at`, `deleted_at`) VALUES
('51', '19', 'Ekspor barang dan jasa', 'persen PDB', '21,7 (2023)', '21.7', '22.6', 'Kementerian Perdagangan', NOW(), NOW(), NULL),
('52', '20', 'Proporsi penduduk kelas menengah', 'persen', '17.13', '17.5', '20', 'Kementerian Koordinator Bidang Pemberdayaan Masyarakat', NOW(), NOW(), NULL),
('53', '20', 'Tingkat kemiskinan', 'persen', '9.03', '7,0-8,0', '4,5-5,0', 'Kementerian Koordinator Bidang Pemberdayaan Masyarakat', NOW(), NOW(), NULL),
('54', '20', 'Tingkat kemiskinan ekstrem', 'persen', '1.47', '0,5-1,0', '0', 'Kementerian Koordinator Bidang Pemberdayaan Masyarakat', NOW(), NOW(), NULL),
('55', '20', 'Penyandang disabilitas yang bekerja di sektor formal', 'persen', '9,07 (2023)', '10', '12', 'Kementerian Ketenagakerjaan', NOW(), NOW(), NULL),
('56', '21', 'Rumah tangga dengan akses hunian layak, terjangkau, dan berkelanjutan', 'persen', '65.25', '67', '74', 'Kementerian Koordinator Bidang Infrastruktur dan Pembangunan Kewilayahan', NOW(), NOW(), NULL),
('57', '22', 'Persentase desa mandiri', 'persen', '22.85', '23.29', '25.79', 'Kementerian Desa dan Pembangunan Daerah Tertinggal', NOW(), NOW(), NULL),
('58', '23', 'Proporsi PDRB Perkotaan terhadap PDB Nasional', 'persen', '56,56 (2022)', '57.29', '59.25', 'Kementerian Koordinator Bidang Infrastruktur dan Pembangunan Kewilayahan', NOW(), NOW(), NULL),
('59', '24', 'Indeks Pembangunan Hukum', NULL, '0,68 (2023)', '0.69', '0.73', 'Kementerian Koordinator Bidang Hukum, Hak Asasi Manusia, Imigrasi dan Pemasyarakatan', NOW(), NOW(), NULL),
('60', '24', 'Indeks Persepsi Korupsi', NULL, '34 (2023)', '38', '43.7', 'Komisi Pemberantasan Korupsi', NOW(), NOW(), NULL),
('61', '24', 'Indeks Integritas Partai Politik', NULL, '62.98', '63,00-64,99', '71,00-72,99', 'Kementerian Koordinator Bidang Politik dan Keamanan', NOW(), NOW(), NULL),
('62', '25', 'Indeks Reformasi Birokrasi Nasional', NULL, '69.98', '71.38', '77.26', 'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi', NOW(), NOW(), NULL),
('63', '25', 'Indeks Pelayanan dan Pelindungan WNI di Luar Negeri', NULL, '93', '93.5', '95.5', 'Kementerian Luar Negeri', NOW(), NOW(), NULL),
('64', '26', 'Angka prevalensi penyalahguna narkotika', NULL, '1.73', '1.7', '1.6', 'Badan Narkotika Nasional', NOW(), NOW(), NULL),
('65', '27', 'Return on Asset (ROA) BUMN', 'persen', '3,14 (2023)', '3.21', '3.42', 'Kementerian Badan Usaha Milik Negara', NOW(), NOW(), NULL),
('66', '28', 'Rasio pendapatan negara terhadap PDB', 'persen', '12.82', '12.36', '13,75-18,00', 'Kementerian Keuangan', NOW(), NOW(), NULL),
('67', '29', 'Tingkat inflasi', 'persen', '1.57', '2,5±1,0', '2,5±1,0', 'Kementerian Koordinator Bidang Perekonomian', NOW(), NOW(), NULL),
('68', '30', 'Indeks Pembangunan Masyarakat (IPMas)', NULL, '62,85 (2021)', '65.49', '68.13', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL),
('69', '31', 'Proporsi kerugian ekonomi langsung akibat bencana relatif terhadap PDB', 'persen', '0,140 (2022)', '0.137', '0.135', 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', NOW(), NOW(), NULL);
